DROP DATABASE IF EXISTS food_swap;

CREATE DATABASE food_swap;

\connect food_swap;


CREATE TABLE users_auth (
  id SERIAL,
  password VARCHAR(256) NOT NULL,
  salt VARCHAR(256) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id SERIAL,
  user_auth_id INTEGER NOT NULL REFERENCES users_auth(id),
  name VARCHAR(25) NOT NULL UNIQUE,
  username VARCHAR(25) NOT NULL UNIQUE,
  picture VARCHAR(255) NULL DEFAULT NULL,
  email VARCHAR(255) NOT NULL,
  bio VARCHAR(255) NULL DEFAULT NULL,
  latitude Float NULL DEFAULT NULL,
  longitude Float NULL DEFAULT NULL,

  rating INTEGER,

  PRIMARY KEY (id)
);

CREATE TABLE food (
  id SERIAL,
  user_id INTEGER NOT NULL REFERENCES users(id),
  dishName VARCHAR(25) NULL DEFAULT NULL,
  description VARCHAR(255) NULL DEFAULT NULL,
  picture VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE friends (
  id SERIAL,
  user_id1 INTEGER NOT NULL REFERENCES users(id),
  user_id2 INTEGER NOT NULL REFERENCES users(id),
  PRIMARY KEY (id)
);

CREATE TABLE trade (
  id SERIAL,
  user_id1 INTEGER NOT NULL REFERENCES users(id),
  food_id1 INTEGER NOT NULL REFERENCES food(id),
  user_id2 INTEGER NOT NULL REFERENCES users(id),
  food_id2 INTEGER NOT NULL REFERENCES food(id),
  trade_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP + INTERVAL '3 hours',
  expired BOOLEAN DEFAULT FALSE,
  accepted BOOLEAN DEFAULT FALSE,
  failed BOOLEAN DEFAULT FALSE,
  user_id1_RATING INTEGER DEFAULT 0 CHECK (user_id1_RATING <= 5),
  user_id2_RATING INTEGER DEFAULT 0 CHECK (user_id1_RATING <= 5),
  PRIMARY KEY (id)
);
